name: colorspark
description: A kids' coloring app
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7        # For SVG rendering
  google_mobile_ads: ^5.1.0  # For ads
  audioplayers: ^5.2.1       # For sounds and music
  shared_preferences: ^2.2.2 # For local storage
  path_provider: ^2.1.1      # For saving files
  image_gallery_saver: ^2.0.3 # For saving to gallery
  share_plus: ^7.2.1         # For sharing
  lottie: ^3.1.0             # For animations
  confetti: ^0.7.0           # For confetti effect
  flutter_lints: ^5.0.0      # For linting
  path_drawing: ^1.0.1      # For drawing paths
  xml: ^6.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/coloring_pages/          # Directory for images
    - assets/sounds/         # Directory for sounds
    - assets/music/background.mp3 
    - assets/animations/         # Directory for Lottie animations